version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8092:3000"
    volumes:
      - ./food_data:/app/food_data
    environment:
      - NODE_ENV=production
      - ADMIN_PASSWORD=123456
