version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8092:3000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
